# General Settings
title: "Miles premium jekyll template"
email: "miles.studio@gmail.com"
favicon: "/assets/img/favicon.png"
description: "Miles - Creative Website"

logo_for_index: /assets/img/logo8.png
logo_for_index_2: /assets/img/logo_13.png
logo_for_index_3: /assets/img/logo_8.png
logo_for_index_4: /assets/img/miles-developer.png
logo_for_index_5: /assets/img/logo_2.png
logo_for_index_6: /assets/img/logo_12.png
logo_for_index_7: /assets/img/logo_3.png
logo_for_index_8: /assets/img/logo_1.png
logo_for_index_9: /assets/img/logo_1.png
logo_for_index_10: /assets/img/logo_1.png
logo_for_index_11: /assets/img/miles-agency-white.png
logo_for_index_12: /assets/img/logo_12.png
logo_for_index_13: /assets/img/logo14.png

address1: "90 Fairground Rd, FL 3290, United States"
phone_number: "+00 (123) 456 78 90"
copyright_text: "© 2022. All Rights Reserved"

google_analytics:
  enable: false
  key: "UA-664136761-1" # UA-664136761-1

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "#"
      icon: "fab fa-facebook-square"

    - url: "#"
      icon: "fab fa-twitter"

    - url: "#"
      icon: "fab fa-behance"

    - url: "#"
      icon: "fab fa-instagram"
